name: Deploy python test in GHA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Installing pytest
        run: |
          pip install pytest
      - name: Running test
        run: |
          python -m pytest
